### ISSUE TITLE
.version file doesn't match current release

### ISSUE THREAD

**Issue by linuxgurugamer** [peteletroll/DockRotate#10]
You apparently updated the .version file in Resources/DockRotate.version for an upcoming release, but never released it.  So KSP-AVC reports that the mod isn't up-to-date

**Comment by peteletroll** [comment]
I usually bumped the version number just after releasing. How wrong I was! I'll fix it as soon as I can (I'm on holiday now)

**Comment by peteletroll** [comment]
Fixed .version file back to 1.4.4.15.
