### ISSUE TITLE
Null reference exception bug making game unplayable.

### ISSUE THREAD

**Issue by jrodrigv** [peteletroll/DockRotate#17]
Hi I'm using KSP 1.6.1 and Dockrotate 1.7.0.37.

When I try to activate the rotation I can this NRE on logs non-stop

[EXC 18:09:45.105] NullReferenceException: Object reference not set to an instance of an object
	DockRotate.Extensions.KJRNextCycleAllAutoStrut (.Vessel v)
	DockRotate.JointMotionObj.onStart ()
	DockRotate.SmoothMotion.advance (Single deltat)
	DockRotate.JointMotion.FixedUpdate ()

**Comment by peteletroll** [comment]
Are you using KJR Next? Which version?

**Comment by jrodrigv** [comment]
I was using the one that is supported my RO team.

https://github.com/KSP-RO/Kerbal-Joint-Reinforcement-Continued

**Comment by peteletroll** [comment]
Could you please try this new dll?
https://www.dropbox.com/s/c0f3rbg58td8lh9/DockRotate.dll?dl=0

**Comment by peteletroll** [comment]
Last release includes a possible fix. Please let me know if it works for you.

**Comment by peteletroll** [comment]
No feedback, assuming bug fixed.

**Comment by jrodrigv** [comment]
Sorry I didn't have to test it yet

**Comment by peteletroll** [comment]
No problem @jrodrigv, just remember to update to the last version when you test it.
